version: "3.3"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
     - 80:80
    depends_on:
      - sample_webapp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./angular-notes-app/dist/angular-notes-app/:/usr/share/nginx/html

  sample_webapp:
    build: ./sample_webapp
    container_name: flask-backend
    restart: always
    environment:
      - FLASK_APP=sample_webapp.py
    ports:
      - 5000:5000

  angular_frontend:
    build:
      context: ./angular-notes-app/
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./angular-notes-app/:/app
