version: "3.3"

services:

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
     - 80:80
    depends_on:
      - sample_webapp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  sample_webapp:
    build: ./sample_webapp
    container_name: flask-backend
    restart: always
    environment:
      - FLASK_APP=sample_webapp.py
    ports:
      - 5000:5000
